ARMvc/Controllers/MaintenanceController.cs
using AlKhalidConnector;
using AlKhalidModels;
using AlKhalidRentalsClient.Helpers;
using ARMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ARMvc.Controllers
{
    [SessionExpiryFilter]
    public class MaintenanceController : Controller
    {
        public ActionResult Index()
        {
            UserModel objUser = Session[SessionConstants.UserSession] as UserModel;
            MaintenanceModel RQ = new MaintenanceModel()
            {
                CardCode = objUser.CardCode,
                CardName = objUser.CardName
            };
            return View(RQ);
        }

        [HttpGet]
        public async Task<ActionResult> PreviousMainatenanceStatus()
        {
            return Json(new ResponseModel() { Status = false, Data = null, Errors = null });
        }

        [HttpPost]
        public async Task<ActionResult> RequestService(MaintenanceModel RQ)
        {
            ServiceCallDataResponseResult oServiceCall = new ServiceCallDataResponseResult();
            oServiceCall.ServiceCallData.Add(new ServiceCall
            {
                CardCode = RQ.CardCode,
                CardName = RQ.CardName,
                Subject = RQ.Subject
            });

            ServiceReponse objResponse = await Connector.RequestMaintenance(oServiceCall) as ServiceReponse;

            if (objResponse is ServiceReponse && objResponse.isSuccess && !string.IsNullOrEmpty(objResponse.ReturnNumber))
            {
                RQ.IsRequested = true;
                RQ.RequestReffNo = objResponse.ReturnNumber;
            }
            return View(@"~\Views\Maintenance\MaintenanceSummary.cshtml", RQ);
        }
    }
}

ARMvc/Controllers/RentController.cs
using AlKhalidConnector;
using AlKhalidModels;
using AlKhalidRentalsClient.Helpers;
using ARMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ARMvc.Controllers
{
    [SessionExpiryFilter]
    public class RentController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> PayRent(PaymentRequestModel RQ)
        {
            UserModel objUser = Session[SessionConstants.UserSession] as UserModel;
            RQ.UDF1 = objUser.CardCode + "" + objUser.CardName;
            RQ.Culture = Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName;

            PaymentResponseModel objResponse = await new PaymentUtility().InitiatePayment(RQ);
            if (objResponse is PaymentResponseModel && string.IsNullOrEmpty(objResponse.ErrorMessage))
            {
                Response.Redirect(objResponse.RedirectionURL);
            }
            return View(@"~\Views\Rent\PayReciept.cshtml", objResponse);
        }

        public ActionResult History()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> RetrieveDueInvoices()
        {
            UserModel objUser = Session[SessionConstants.UserSession] as UserModel;
            RentHistory objInvoices = await Connector.GetRentDues(objUser) as RentHistory;
            List<Invoicesdata> lsInvoices = new List<Invoicesdata>();
            if (objInvoices != null && objInvoices.Result != null && objInvoices.Result.InvoicesData != null)
            {
                lsInvoices = objInvoices.Result.InvoicesData.ToList();
            }
            return Json(new ResponseModel() { Status = false, Data = lsInvoices, Errors = null }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> RetrieveHistoricInvoices()
        {
            UserModel objUser = Session[SessionConstants.UserSession] as UserModel;
            RentHistory objInvoices = await Connector.GetRentHistory(objUser) as RentHistory;
            List<Invoicesdata> lsInvoices = new List<Invoicesdata>();
            if (objInvoices != null && objInvoices.Result != null && objInvoices.Result.InvoicesData != null)
            {
                lsInvoices = objInvoices.Result.InvoicesData.ToList();
            }
            return Json(new ResponseModel() { Status = false, Data = lsInvoices, Errors = null }, JsonRequestBehavior.AllowGet);
        }
    }
}

ARMvc/Views/Shared/_FooterPartial.cshtml
@using ARMvc.Helpers;
<!-- Page Footer-->
<footer class="section footer-classic context-dark">
    <div class="container">
        <ul>
            <li class="active"><a href="@Url.Action("ChangePassword", "Account")">@Html.Resource("ChangePassword")</a></li>
            <li><a href="@Url.Action("Index", "Maintenance")">@Html.Resource("MaintenanceRequest")</a></li>
            <li><a href="@Url.Action("Index", "Rent")">@Html.Resource("PayRent")</a></li>
            @*<li><a href="#" onclick="return fnChangeCulture();">@Html.Resource("Language")</a></li>
                <li><a href="#">@Html.Resource("Logout")</a></li>*@
        </ul>
        <ul>
            <li>
                <!-- Rights-->
                <p>
                    <span>©&nbsp;</span>
                    <span>@DateTime.Now.Year</span>
                    <span>&nbsp;</span>
                    <span>@Html.Resource("AlKhalid")</span>
                    <span>&nbsp;</span>
                    @*<a href="#">Privacy Policy</a>*@
                    <span>&nbsp;</span>
                    <a href="mailto:info@alkhalid.com">info@alkhalid.com</a>
                </p>
            </li>
        </ul>
    </div>
</footer>
<!-- Popup overlay loader start here-->
<div class="overlay">
    <div class="loaderDiv">
        <div class="sk-fading-circle">
            <div class="sk-circle1 sk-circle"></div>
            <div class="sk-circle2 sk-circle"></div>
            <div class="sk-circle3 sk-circle"></div>
            <div class="sk-circle4 sk-circle"></div>
            <div class="sk-circle5 sk-circle"></div>
            <div class="sk-circle6 sk-circle"></div>
            <div class="sk-circle7 sk-circle"></div>
            <div class="sk-circle8 sk-circle"></div>
            <div class="sk-circle9 sk-circle"></div>
            <div class="sk-circle10 sk-circle"></div>
            <div class="sk-circle11 sk-circle"></div>
            <div class="sk-circle12 sk-circle"></div>
        </div>
    </div>
</div>
<!-- Popup overlay loader ends here-->

ARMvc/Views/Shared/_HeaderPartial.cshtml
@using ARMvc.Helpers;
@{ 
    AlKhalidModels.UserModel objUser = Session[AlKhalidRentalsClient.Helpers.SessionConstants.UserSession] as AlKhalidModels.UserModel;
    string branchName = objUser.CardCode + "-" + objUser.CardName;
}
<!-- Page Header-->
<header class="page-header">
    <div class="container-fluid">
        <div class="row align-item-center">
            <div class="col-lg-4 col-md-8 col-sm-9 col-10">
                <div class="LogWidth" onclick="window.location.href='@Url.Action("Index", "Home")'">
                    <div class="logo">
                        <img src="~/Content/images/al_khalid-logo.png" >
                        <span>@Html.Resource("AlKhalid")</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-md-4 col-sm-3 col-2">
                <div class="MobTopMenu">
                    <span><i><img src="~/Content/images/Mob_menu.png"></i></span>
                </div>
                <div class="MenuOverlay"></div>
                <ul class="menu">
                    <li class="active"><a href="@Url.Action("Index", "Home")">@*@Html.Resource("Home")*@@branchName</a></li>
                    <li><a href="@Url.Action("Index", "Maintenance")">@Html.Resource("MaintenanceRequest")</a></li>
                    <li><a href="@Url.Action("Index", "Rent")">@Html.Resource("PayRent")</a></li>
                    <li><a href="@Url.Action("SignOut", "Account")">@Html.Resource("Logout")</a></li>
                    <li><a onclick="return fnChangeCulture('@Request.Url.AbsoluteUri');">@Html.Resource("Language")</a></li>
                </ul>
            </div>
        </div>
    </div>
</header>
<script src="~/Scripts/Home.js"></script>
<input type="hidden" id="hdf_Culture_URL" value="@Url.Action("ChangeCulture", "Account")" />

ARMvc/Views/Shared/_Layout.cshtml
@using ARMvc.Helpers;
@using System.Threading;
@{ 
    string culture = Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName == "en" ? "ar" : "en";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Site Title-->
    <title>@Html.Resource("AlKhalid")</title>
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <!-- Fav Icon-->
    <link rel="icon" href="~/Content/images/favicon.png" type="image/x-icon">
    <!-- Stylesheets-->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rufina:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/css/fonts.css">
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/css/style_@(culture).css">
</head>
<body>
    @{ Html.RenderPartial("_HeaderPartial"); }

    <main role="main">
        @RenderBody()
    </main>

    @{ Html.RenderPartial("_FooterPartial"); }
    @*<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.1/knockout-latest.min.js'></script>*@
    <script src="~/Scripts/knockout/knockout-3.5.1.js"></script>
    <!-- Javascript-->
    <script src='~/Scripts/jquery.min.js'></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <script src="~/Scripts/AllPage.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>